#!/bin/bash

echo "🚀 Fitness Tracker - OkHttp Profiler Test"
echo "=========================================="
echo ""
echo "This script helps you test the OkHttp Profiler integration with OpenRouter API"
echo ""

echo "📱 Prerequisites:"
echo "1. Android Studio with OkHttp Profiler plugin installed"
echo "2. App running in debug mode"
echo "3. Device/emulator connected"
echo ""

echo "🔧 OkHttp Profiler Plugin Setup:"
echo "1. In Android Studio: File → Settings → Plugins"
echo "2. Search for 'OkHttp Profiler'"
echo "3. Install and restart Android Studio"
echo ""

echo "📊 Testing Network Profiling:"
echo "1. Run the app in debug mode"
echo "2. Navigate to 'AI Food Analysis' screen"
echo "3. Take a photo or select image from gallery"
echo "4. Click 'Analyze Food Image' button"
echo "5. Look for 'OkHttp Profiler' tab at bottom of Android Studio"
echo ""

echo "🔍 What You'll See in OkHttp Profiler:"
echo "• Request URL: https://openrouter.ai/api/v1/chat/completions"
echo "• Request Headers: Authorization, Content-Type"
echo "• Request Body: JSON with model, messages, and base64 image"
echo "• Response: AI analysis results from OpenRouter"
echo "• Timing: Request duration and performance metrics"
echo ""

echo "📝 Sample Request Structure:"
echo "{"
echo "  \"model\": \"qwen/qwen-2.5-vl-7b-instruct\","
echo "  \"messages\": ["
echo "    {"
echo "      \"role\": \"user\","
echo "      \"content\": ["
echo "        {"
echo "          \"type\": \"text\","
echo "          \"text\": \"You are an AI that analyzes images of food...\""
echo "        },"
echo "        {"
echo "          \"type\": \"image_base64\","
echo "          \"image_base64\": \"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD...\""
echo "        }"
echo "      ]"
echo "    }"
echo "  ]"
echo "}"
echo ""

echo "✅ Benefits of OkHttp Profiler:"
echo "• Debug API requests in real-time"
echo "• Monitor network performance"
echo "• Troubleshoot authentication issues"
echo "• Verify request/response payloads"
echo "• Track API call timing"
echo ""

echo "🎯 Next Steps:"
echo "1. Install OkHttp Profiler plugin"
echo "2. Run app in debug mode"
echo "3. Test food image analysis"
echo "4. Monitor network calls in profiler"
echo "5. Debug any issues with request/response"
echo ""

echo "🔗 Useful Links:"
echo "• OkHttp Profiler Plugin: https://plugins.jetbrains.com/plugin/11192-okhttp-profiler"
echo "• OpenRouter API Docs: https://openrouter.ai/docs"
echo "• OkHttp Documentation: https://square.github.io/okhttp/"
echo ""

echo "Happy Debugging! 🐛✨"
